name: Deploy to GitHub Pages

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  test-deploy:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test build website
        run: yarn build
  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          #ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }} 
          ssh-private-key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHUwifeBMj4n1jOxLedKvV/3o9rkTdIOpd7UsHro6MPG 1214658495@qq.com
      - name: Deploy to GitHub Pages
        env:
          USE_SSH: true
        run: |
          git config --global user.email "1214658495@qq.com"
          git config --global user.name "1214658495"
          yarn install --frozen-lockfile
          yarn deploy