# name: Deploy to GitHub Pages

# on:
#   pull_request:
#     branches: [main]
#   push:
#     branches: [main]

# permissions:
#   contents: write

# jobs:
#   test-deploy:
#     if: github.event_name != 'push'
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 18
#           cache: yarn
#       - name: Install dependencies
#         run: yarn install --frozen-lockfile
#       - name: Test build website
#         run: yarn build
#   deploy:
#     if: github.event_name != 'pull_request'
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 18
#           cache: yarn
#       - uses: webfactory/ssh-agent@v0.5.0
#         with:
#           ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }} 
#       - name: Deploy to GitHub Pages
#         env:
#           USE_SSH: true
#         run: |
#           git config --global user.email "1214658495@qq.com"
#           git config --global user.name "1214658495"
#           yarn install --frozen-lockfile
#           yarn deploy



name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # Workflow syntax for GitHub Actions - GitHub Docs

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4